<?php
/**
 * Страница "Список модулей".
 * 
 * Английская (британская) локализация.
 * 
 * Этот файл является частью расширения модуля веб-приложения RosGear.
 * 
 * @copyright Copyright (c) 2015 RosGear
 * @license https://rosgear.ru/license/
 */
?>
<article>
    <h1>List of modules</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/grid.png' ?>" />
    </div>
    <p>The list of modules is dynamically generated based on the active filter: either installed modules, uninstalled modules, or both categories are displayed.</p>
    <h2>List columns</h2>
    <ul class="g-help-list">
        <li><b>Name.</b> Module name, description, and version;</li>
        <li><b>Identifier.</b> Unique module identifier;</li>
        <li><b>Path.</b> Local path to the installed module;</li>
        <li><b>Route.</b> Module call route (a rule linking a URL to a module handler);</li>
        <li><b>Author.</b> Module author;</li>
        <li><b>Version.</b> Module version;</li>
        <li><b>Purpose.</b> Module purpose: Control panel, Website;</li>
        <li><b>Enabled.</b> Indicates whether the module is currently capable of receiving and processing requests;</li>
        <li><b>Visible.</b> Module visibility in the Control Panel or on the website;</li>
        <li><b>Status.</b> Module status: installed, not installed, error, unknown.</li>
    </ul>

    <h2>Toolbar</h2>
    <ul class="g-help-list">
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-install.svg' ?>" /> <b>Install.</b> Opens the form to install the selected module from the list;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-uninstall.svg' ?>" /> <b>Uninstall.</b> Completely removes the installed module;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-delete.svg' ?>" /> <b>Delete.</b> Removes the loaded module package;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-unmount.svg' ?>" /> <b>Unmount.</b> Unmount (uninstalls) an installed module without deleting it from the repository;</li>
      <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-download.svg' ?>" /> <b>Download.</b> Downloads the module package corresponding to the item selected in the list;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-upload.svg' ?>" /> <b>Upload.</b> Uploads the module package file for subsequent installation;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-edit.svg' ?>" /> <b>Edit.</b> Opens the module editing form;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-select.svg' ?>" /> <b>Select.</b> Selects or deselects modules in the list;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/refresh.svg' ?>" /> <b>Refresh.</b> Refresh the list of modules;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-update-config.svg' ?>" /> <b>Refresh.</b> Updates the configuration of installed modules. Used when changes are made to the configuration files of modules or the application;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-profiling-off.svg' ?>" /> <b>Record profiling.</b> Expands or collapses the navigation panel to display module information;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-toggle-columns-off.svg' ?>" /> <b>Show / Hide.</b> Shows or hides columns that are hidden by default;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/help.svg' ?>" /> <b>Help.</b> Opens the reference information window for the current list;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/search.svg' ?>" /> <b>Search.</b> Opens the module search form within the list;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/filter.svg' ?>" /> <b>Filter.</b> Filters the list of modules based on their installation status: displays either installed or uninstalled modules (depending on the selected criterion).</li>
    </ul>
</article>