<?php
/**
 * Страница "Список модулей".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью расширения модуля веб-приложения RosGear.
 * 
 * @copyright Copyright (c) 2015 RosGear
 * @license https://rosgear.ru/license/
 */
?>
<article>
    <h1>Список модулей</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/grid.png' ?>" />
    </div>
    <p>Список модулей динамически формируется в соответствии с активным фильтром: отображаются либо установленные, либо не установленные модули, либо обе категории.</p>
    <h2>Столбцы списка</h2>
    <ul class="g-help-list">
        <li><b>Название.</b> Название, описание и версия модуля;</li>
        <li><b>Идентификатор.</b> Уникальный идентификатор модуля;</li>
        <li><b>Путь.</b> Локальный путь к установленному модулю;</li>
        <li><b>Маршрут.</b> Маршрут (правило, которое связывает URL с обработчиком модуля) вызова модуля;</li>
        <li><b>Автор.</b> Автор модуля;</li>
        <li><b>Версия.</b> Версия модуля;</li>
        <li><b>Назначение.</b> Назначение модуля: Панель управления, Сайт;</li>
        <li><b>Доступность.</b> Указывает, способен ли модуль принимать и обрабатывать запросы в текущий момент;</li>
        <li><b>Видимость.</b> Видимость модуля в Панели управления или на сайте;</li>
        <li><b>Статус.</b> Статус модуля: установлен, не установлен, ошибка, неизвестно.</li>
    </ul>

    <h2>Панель инструментов</h2>
    <ul class="g-help-list">
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-install.svg' ?>" /> <b>Установить.</b> Вызывает форму для установки выбранного модуля из списка;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-uninstall.svg' ?>" /> <b>Удалить.</b> Полностью удаляет установленный модуль;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-delete.svg' ?>" /> <b>Удалить.</b> Удаляет пакет загруженного модуля;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-unmount.svg' ?>" /> <b>Демонтаж.</b> Удаляет (деинсталлирует) установленный модуль без удаления его из репозитория;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-download.svg' ?>" /> <b>Скачать.</b> Скачивает пакет модуля, соответствующий элементу, выделенному в списке;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-upload.svg' ?>" /> <b>Загрузить.</b> Загружает файл пакета модуля для дальнейшей установки;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-edit.svg' ?>" /> <b>Правка.</b> Вызывает форму для редактирования модуля;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-select.svg' ?>" /> <b>Выделить.</b> Выделяет или убирает выделение модулей в списке;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/refresh.svg' ?>" /> <b>Обновить.</b> Обновляет список модулей;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-update-config.svg' ?>" /> <b>Обновить.</b> Выполняет обновление конфигурации установленных модулей. Используется при внесении изменений в файлы конфигурации модулей или приложения;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-profiling-off.svg' ?>" /> <b>Профилирование записи.</b> Разворачивает или сворачивает Панель навигации для отображения информации о модуле;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-toggle-columns-off.svg' ?>" /> <b>Показать / Скрыть.</b> Показывает или скрывает столбцы, которые скрыты по умолчанию;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/help.svg' ?>" /> <b>Справка.</b> Открывает окно справочной информации для текущего списка;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/search.svg' ?>" /> <b>Поиск.</b> Открывает форму поиска модулей в списке;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/filter.svg' ?>" /> <b>Фильтр.</b> Выполняет фильтрацию списка модулей по признаку их установки: отображаются либо установленные, либо не установленные модули (в зависимости от выбранного критерия).</li>
    </ul>
</article>