<?php
/**
 * Страница "Содержание".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью модуля веб-приложения RosGear.
 * 
 * @copyright Copyright (c) 2015 RosGear
 * @license https://rosgear.ru/license/
 */
?>
<article>
    <h1>Менеджер модулей</h1>
    <div class="g-help-icon">
        <img src="<?= $assetsUrl, '/images/icon.svg' ?>" />
    </div>
    <p>Менеджер выполняет: установку, удаление и демонтаж модулей веб-приложения.</p>

    <h2>Содержание:</h2>
    <ul class="g-help-list">
        <li><a href="<?= $url('grid') ?>">Список модулей</a></li>
        <li><a href="<?= $url('edit') ?>">Форма редактирования модуля</a></li>
        <li><a href="<?= $url('install') ?>">Форма установки модуля</a></li>
    </ul>
</article>