<?php
/**
 * Страница "Установка модуля".
 * 
 * Локализации по умолчанию.
 * 
 * Этот файл является частью модуля веб-приложения RosGear.
 * 
 * @copyright Copyright (c) 2015 RosGear
 * @license https://rosgear.ru/license/
 */
?>
<article>
    <h1>Installing a module</h1>
    <p>The form appears after clicking on the <b>"Install"</b> button on the toolbar <a href="<?= $url('grid') ?>">list of modules</a>.</p>
    <h2>Form tabs</h2>
    <h3>Tab "Information"</h3>
    <p>The tab displays information about the version, purpose of the module, author, and installation requirements.</p>

    <h3>Tab "Configuration"</h3>
    <p>The tab will display the main configuration parameters of the module and the choice of installation in the Partitions panel.</p>

    <h3>Tab "Permissions"</h3>
    <p>The tab displays the access rights (permissions) of the installed module. The selected user roles will have full access (<b>"any"</b> permission) to the module.</p>
</article>